name: intl_translation_ota_flutter
description: Load translations over the air.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: '>=0.15.3 <0.17.0'
  intl_translation:
    git:
      url: https://github.com/jamesblasco/intl_translation/
      ref: gsoc
  intl_translation_format:
    path: './../../intl_translation_format'
  intl_translation_ota:
    path: './../intl_translation_ota'  

dev_dependencies:
  analyzer: '>=0.36.0 <0.40.0'
  args: '>=0.12.1 <2.0.0'
  dart_style: ^1.0.0
  path: '>=0.9.0 <2.0.0'
  petitparser: '>=1.1.3 < 3.0.2'
