name: intl_translation_format
description: This package provides multiformat support for the Intl package
version: 0.0.1+2
homepage: https://github.com/jamesblasco/intl_translation_format

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  intl_translation: ^0.17.10+1
  intl_translation_arb: ^0.0.1
  intl_translation_xliff: ^0.0.1
  yaml: ^2.2.1
  test: ^1.15.1
  path: '>=0.9.0 <2.0.0'
  petitparser: '>=1.1.3 < 3.0.2'
  args: '>=0.12.1 <2.0.0'
  meta: '>=0.9.0 <2.0.0'

dev_dependencies:
  analyzer: '>=0.36.0 <0.40.0'
  dart_style: ^1.0.0
  intl: '>=0.15.3 <0.17.0'
