name: intl_translation_builder
description: Extract messages to a xliff file and generate translations from xliff files
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  intl_translation:
    git:
      url: https://github.com/jamesblasco/intl_translation/
      ref: gsoc
  intl_translation_format:
    path: './../../intl_translation_format'
  build: ^1.1.6

dev_dependencies:
  build_config: ^0.4.1+1
  build_runner: ^1.6.6
  analyzer: '>=0.36.0 <0.40.0'
  args: '>=0.12.1 <2.0.0'
  dart_style: ^1.0.0
  intl: '>=0.15.3 <0.17.0'
  path: '>=0.9.0 <2.0.0'
  petitparser: '>=1.0.0 < 4.0.0'
  pedantic: ^1.8.0


intl_translation:
  project_name: intl_messages
  output_dir: ./lib/l10n/
  format: json
  default_locale: en
  sources:
    - lib/main.dart
  translations:
    - lib/l10n/intl_messages_es.json
    - lib/l10n/intl_messages_en.json
  
  